"""Update chat sessions

Revision ID: 1274fcd6779a
Revises: 5d1a033341c5
Create Date: 2023-12-05 14:49:40.527428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1274fcd6779a'
down_revision = '5d1a033341c5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
