"""Add recipeDP.userID

Revision ID: 17af93792b42
Revises: 276f8508c82b
Create Date: 2023-12-08 09:24:40.024681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17af93792b42'
down_revision = '276f8508c82b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe_dps', sa.Column('userID', sa.String(length=60), nullable=False))
    op.create_foreign_key(None, 'recipe_dps', 'users', ['userID'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipe_dps', type_='foreignkey')
    op.drop_column('recipe_dps', 'userID')
    # ### end Alembic commands ###
