"""Handle dp orphans

Revision ID: 276f8508c82b
Revises: 85c228eebee8
Create Date: 2023-12-07 15:45:14.372410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '276f8508c82b'
down_revision = '85c228eebee8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
