"""Remove UserDP

Revision ID: 29c53a093546
Revises: 307aa483d433
Create Date: 2023-12-07 09:14:27.123163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29c53a093546'
down_revision = '307aa483d433'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('dp', sa.String(length=384), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'dp')
    # ### end Alembic commands ###
