"""Add new tables

Revision ID: 429982b78af1
Revises: 7dcc23325ee5
Create Date: 2023-12-07 06:48:27.802430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '429982b78af1'
down_revision = '7dcc23325ee5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
