"""Create chat sessions

Revision ID: 5d1a033341c5
Revises: c27938126d12
Create Date: 2023-12-05 14:47:21.956033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d1a033341c5'
down_revision = 'c27938126d12'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'chats', 'chat_sessions', ['sessionID'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chats', type_='foreignkey')
    # ### end Alembic commands ###
