"""Fix sessions bug

Revision ID: 7dcc23325ee5
Revises: 1274fcd6779a
Create Date: 2023-12-05 14:57:32.858781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dcc23325ee5'
down_revision = '1274fcd6779a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
