"""Update user db model

Revision ID: 85c228eebee8
Revises: 29c53a093546
Create Date: 2023-12-07 14:51:14.879974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85c228eebee8'
down_revision = '29c53a093546'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
