"""Update table

Revision ID: c27938126d12
Revises: 
Create Date: 2023-12-05 10:47:11.567634

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c27938126d12'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('content', sa.Text(), nullable=False))
    op.add_column('chats', sa.Column('role', sa.String(length=100), nullable=False))
    op.drop_column('chats', 'chat')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('chat', mysql.TEXT(), nullable=False))
    op.drop_column('chats', 'role')
    op.drop_column('chats', 'content')
    # ### end Alembic commands ###
