"""Update dps

Revision ID: fd48a2f143d4
Revises: 429982b78af1
Create Date: 2023-12-07 06:58:24.011088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd48a2f143d4'
down_revision = '429982b78af1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
