export const TeamMembers = [
  {
    id: 1,
    name: "Mike",
    role: "Backend Architect",
    passion: "fullstack Dev",
    image: "mike.jpg",
  },
  {
    id: 2,
    name: "George",
    role: "Algorithm Architect",
    passion: "Fullstack dev",
    image: "Gorge.JPG",
  },
  {
    id: 3,
    name: "Success",
    role: "Interface Virtuoso",
    passion: "Fullstack dev",
    image: "success.jpg",
  },
  {
    id: 4,
    name: "Felicia",
    role: "Data Sorceress",
    passion: "Data Scientist",
    image: "felicia.jpg",
  },
  {
    id: 5,
    name: "Sani",
    role: "Access Control Guru",
    passion: "Fullstack dev",
    image: "sani.jpg",
  },
  {
    id: 6,
    name: "Sunkanmi",
    role: "Server-side Sage",
    passion: "Fullstack Dev",
    image: "sunkanmi.JPG",
  },
];


export const africanCuisines = [
  { "value": "algerian", "label": "Algerian", "checked": false },
  { "value": "angolan", "label": "Angolan", "checked": false },
  { "value": "beninese", "label": "Beninese", "checked": false },
  { "value": "botswanan", "label": "Botswanan", "checked": false },
  { "value": "burkinabe", "label": "Burkinabe", "checked": false },
  { "value": "burundian", "label": "Burundian", "checked": false },
  { "value": "cabo_verdean", "label": "Cabo Verdean", "checked": false },
  { "value": "cameroonian", "label": "Cameroonian", "checked": false },
  { "value": "central_african", "label": "Central African", "checked": false },
  { "value": "chadian", "label": "Chadian", "checked": false },
  { "value": "comoran", "label": "Comoran", "checked": false },
  { "value": "congolese", "label": "Congolese", "checked": false },
  { "value": "djiboutian", "label": "Djiboutian", "checked": false },
  { "value": "egyptian", "label": "Egyptian", "checked": false },
  { "value": "equatorial_guinean", "label": "Equatorial Guinean", "checked": false },
  { "value": "eritrean", "label": "Eritrean", "checked": false },
  { "value": "eswatini", "label": "Eswatini", "checked": false },
  { "value": "ethiopian", "label": "Ethiopian", "checked": false },
  { "value": "gabonese", "label": "Gabonese", "checked": false },
  { "value": "gambian", "label": "Gambian", "checked": false },
  { "value": "ghanaian", "label": "Ghanaian", "checked": false },
  { "value": "guinean", "label": "Guinean", "checked": false },
  { "value": "guinea_bissauan", "label": "Guinea-Bissauan", "checked": false },
  { "value": "ivorian", "label": "Ivorian", "checked": false },
  { "value": "kenyan", "label": "Kenyan", "checked": false },
  { "value": "lesothoan", "label": "Lesothoan", "checked": false },
  { "value": "liberian", "label": "Liberian", "checked": false },
  { "value": "libyan", "label": "Libyan", "checked": false },
  { "value": "malagasy", "label": "Malagasy", "checked": false },
  { "value": "malawian", "label": "Malawian", "checked": false },
  { "value": "malian", "label": "Malian", "checked": false },
  { "value": "mauritanian", "label": "Mauritanian", "checked": false },
  { "value": "mauritian", "label": "Mauritian", "checked": false },
  { "value": "moroccan", "label": "Moroccan", "checked": false },
  { "value": "mozambican", "label": "Mozambican", "checked": false },
  { "value": "namibian", "label": "Namibian", "checked": false },
  { "value": "nigerien", "label": "Nigerien", "checked": false },
  { "value": "nigerian", "label": "Nigerian", "checked": false },
  { "value": "rwandan", "label": "Rwandan", "checked": false },
  { "value": "sao_tomean", "label": "Sao Tomean", "checked": false },
  { "value": "senegalese", "label": "Senegalese", "checked": false },
  { "value": "seychellois", "label": "Seychellois", "checked": false },
  { "value": "sierra_leonean", "label": "Sierra Leonean", "checked": false },
  { "value": "somali", "label": "Somali", "checked": false },
  { "value": "south_african", "label": "South African", "checked": false },
  { "value": "south_sudanese", "label": "South Sudanese", "checked": false },
  { "value": "sudanese", "label": "Sudanese", "checked": false },
  { "value": "tanzanian", "label": "Tanzanian", "checked": false },
  { "value": "togolese", "label": "Togolese", "checked": false },
  { "value": "tunisian", "label": "Tunisian", "checked": false },
  { "value": "ugandan", "label": "Ugandan", "checked": false },
  { "value": "zambian", "label": "Zambian", "checked": false },
  { "value": "zimbabwean", "label": "Zimbabwean", "checked": false }
]

export const filters = [
  {
    id: "cuisines",
    name: "Cuisines",
    options: africanCuisines,
  },
  {
    id: "ingredients",
    name: "Ingredients",
    options: [
      { value: "onion", label: "Onion", checked: false },
      { value: "tomato", label: "Tomato", checked: false },
      { value: "vegetable", label: "Vegetable", checked: true },
      { value: "ginger", label: "Ginger", checked: false },
      { value: "curry", label: "Curry", checked: false },
    ],
  },
  {
    id: "cookTime",
    name: "Cooking Time",
    options: [
      { value: "10", label: "10 Minutes", checked: false },
      { value: "15", label: "15 Minutes", checked: false },
      { value: "20", label: "20 Minutes", checked: false },
      { value: "30", label: "30 Minutes", checked: false },
      { value: "45", label: "45 Minutes", checked: false },
      { value: "60", label: "60 Minutes", checked: true },
    ],
  },
];
